# Generated by Django 4.0.4 on 2022-05-29 21:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('logo', models.CharField(max_length=255)),
                ('value', models.FloatField()),
                ('tax', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('value', models.FloatField()),
                ('type', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conversor.user')),
            ],
        ),
        migrations.CreateModel(
            name='Mile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('balance', models.FloatField()),
                ('expiresIn', models.DateField()),
                ('brandId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conversor.brand')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conversor.user')),
            ],
        ),
    ]
