# Generated by Django 4.0.4 on 2022-05-29 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='tax',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='value',
        ),
    ]
