# Generated by Django 4.0.4 on 2022-05-29 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversor', '0003_brand_tax_brand_value_alter_mile_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
